on: [push, pull_request]

name: Website Check

jobs:
  "Check_Website":
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Naev Website Repository
      uses: actions/checkout@v2

    - name: Update APT Cache
      run: |
        sudo apt-get update

    - name: Install Required APT Packages
      run: |
        sudo apt-get install \
          bundler \
          make \
          ruby-dev \
          tidy

    - name: Install Required Ruby Gems
      run: |
        bundle install -j$(nproc)

    - name: Build and Check Website
      run: |
        make check

    - name: Upload Crash Log
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: naev-website-${{ github.sha }}-crashlog
        path: ${{ github.workspace }}/crash.log
        if-no-files-found: error

    - name: Upload Website Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: naev-website-crashlog-${{ github.sha }}
        path: ${{ github.workspace }}/output/*
        if-no-files-found: error
